version: "3"
services:
  webapp:
    image: obeliks4j-classla-stanfordnlp:latest
    ports:
        - 127.0.0.1:5000:80
    environment:
        - DATA_DIR=/data
    volumes:
        - /opt/marcell-pipeline/data:/data
        - /opt/marcell-pipeline/models:/pipeline/models
